version: "3.9"
services:
  project:
    build:
      context: ./project
    container_name: project
    environment:
      - VITE_API_URL=https://api.project.com
    restart: on-failure
    ports:
      - '3000:3000'